version: '3.7'

services:
  db:
    container_name: tpbdm_pg_database
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepasswd
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    container_name: tpbdm_adminer
    image: dockette/adminer:full
    restart: always
    ports:
      - '5051:80'

  scraper:
    container_name: tpbdm_scraper
    build: ./scraper
    image: tpbdm_scraper:latest
    restart: always
    environment:
      PORT: 8081
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: securepasswd
      DB_DATABASE: tpbdm
      OPENAQ_URL: https://api.openaq.org/v1
    ports:
      - '8081:8081'
    depends_on:
      - db
