name: PUSH

on:
  push:
    branches: [main]

jobs:

  Lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Pull project
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true
          working-directory: scraper
          args: --timeout=3m

  Test:
    name: Run unit tests on scraper
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Pull project
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Test scraper
        run: |
          cd scraper
          go test -v ./...
